### ISSUE TITLE
请求添加 CORS 支持

### ISSUE THREAD

**Issue by RedBeanN** [mamoe/mirai-api-http#15]
`Access to XMLHttpRequest at 'http://127.0.0.1:8081/auth' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
添加 `Access-Control-Allow-Origin` 用于前端跨域请求直接调用 mirai

配置类似：
```yaml
authKey: foobarbaz
port: 8081
CORS: 127.0.0.1:8080
```
