### ISSUE TITLE
setting.yml结构已变，需要更新Readme

### ISSUE THREAD

**Issue by EvolvedGhost** [mamoe/mirai-api-http#756]
更新到最新版（2.10.0）后发现原配置不能使用，删除文件后发现其默认配置已变为

```
cors: 
  - '*'
host: 0.0.0.0
port: 8080
authKey: INITKEY143vL21i
cacheSize: 4096
enableWebsocket: false
report: 
  enable: false
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: []
  extraHeaders: {}

heartbeat: 
  enable: false
  delay: 1000
  period: 15000
  destinations: []
  extraBody: {}

  extraHeaders: {}
```
