### ISSUE TITLE
上报服务setting出错

### ISSUE THREAD

**Issue by IMNOTHD** [mamoe/mirai-api-http#84]
```yaml
# 可选，上报服务
report:
  # 可选，是否启用上报，默认不启用
  enable: false
  # 可选，上报群消息的配置
  groupMessage:
    # 可选，是否上报，默认不上报
    report: true
  # 可选，上报好友消息的配置
  friendMessage:
    # 可选，是否上报，默认不上报
    report: true
  # 可选，上报事件消息的配置
  eventMessage:
    report: true
  # 必选，上报的地址列表
  destinations:
    - https://postman-echo.com/post
  # 可选，上报时需要带上的请求头
  extraHeaders:
    # 填上你需要的请求头（如授权信息等）
    Authorization: basic xxx

# 可选，心跳服务
heartbeat:
  # 可选，是否启用心跳，默认不启用
  enable: true
  # 可选，心跳启动延迟，默认1000
  delay: 1000
  # 可选，心跳周期，默认15000
  period: 15000
  # 必选，心跳PING的地址列表
  destinations:
    - https://postman-echo.com/post
  # 可选，心跳PING时需要带上的请求体
  extraBody:
    # 填上你需要的请求体（如QQ等信息）
    qq: 775150
  # 可选，心跳PING时需要带上的请求头
  extraHeaders:
    # 填上你需要的请求头（如授权信息等）
    Authorization: basic xxx
```

> [0m 20:54:36 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: true[39;49m
> [0m 20:54:36 [INFO] [MiraiAPIHTTP] 上报模块启用状态: true[39;49m

```yaml
# 可选，上报服务
report:
  # 可选，是否启用上报，默认不启用
  enable: true
  # 可选，上报群消息的配置
  groupMessage:
    # 可选，是否上报，默认不上报
    report: true
  # 可选，上报好友消息的配置
  friendMessage:
    # 可选，是否上报，默认不上报
    report: true
  # 可选，上报事件消息的配置
  eventMessage:
    report: true
  # 必选，上报的地址列表
  destinations:
    - https://postman-echo.com/post
  # 可选，上报时需要带上的请求头
  extraHeaders:
    # 填上你需要的请求头（如授权信息等）
    Authorization: basic xxx

# 可选，心跳服务
heartbeat:
  # 可选，是否启用心跳，默认不启用
  enable: false
  # 可选，心跳启动延迟，默认1000
  delay: 1000
  # 可选，心跳周期，默认15000
  period: 15000
  # 必选，心跳PING的地址列表
  destinations:
    - https://postman-echo.com/post
  # 可选，心跳PING时需要带上的请求体
  extraBody:
    # 填上你需要的请求体（如QQ等信息）
    qq: 775150
  # 可选，心跳PING时需要带上的请求头
  extraHeaders:
    # 填上你需要的请求头（如授权信息等）
    Authorization: basic xxx
```

> [0m 20:57:33 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: false[39;49m
> [0m 20:57:33 [INFO] [MiraiAPIHTTP] 上报模块启用状态: false[39;49m

使用mirai-console-wrapper-1.2.0-all.jar和mirai-api-http-v1.7.0.jar
